//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHeavenAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<short> StaffID { get; set; }
        public Nullable<short> CustomerID { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public Nullable<System.DateTime> RequestedDateTime { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
    }
}
