//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHeavenAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomPizza
    {
        public string CustomPizzaName { get; set; }
        public string SizeName { get; set; }
        public string BaseName { get; set; }
        public string CrustName { get; set; }
        public string SauceName { get; set; }
        public string CheeseName { get; set; }
        public string CustomPizzaImage { get; set; }
    }
}
