
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PizzaHeavenAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public short CustomerID { get; set; }

    public string Firstname { get; set; }

    public string Surname { get; set; }

    public Nullable<System.DateTime> dob { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string CustomerPassword { get; set; }

    public string DeliveryAddressLineOne { get; set; }

    public string DeliveryAddressLineTwo { get; set; }

    public string DeliveryCity { get; set; }

    public string DeliveryCounty { get; set; }

    public string DeliveryPostCode { get; set; }

    public string Salt { get; set; }

    public string PrivateKey { get; set; }

}

}
