//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHeavenAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaSize
    {
        public string SizeName { get; set; }
        public string SizeDescription { get; set; }
        public Nullable<decimal> SizePrice { get; set; }
    }
}
