//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHeavenAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public short StaffID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string CompanyPosition { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public string StaffPassword { get; set; }
        public string Salt { get; set; }
        public string PrivateKey { get; set; }
        public string Employed { get; set; }
    }
}
